services:
  universibo_campus.api.client:
    class: 'Guzzle\Http\Client'
    public: false
    arguments:
      - '%universibo_campus.api.url%'

  universibo_campus.retriever.guzzle:
    class: 'Universibo\Bundle\CampusBundle\Data\GuzzleDataRetriever'
    public: false
    arguments:
      - '@universibo_campus.api.client'

  universibo_campus.api.facade:
    class: 'Universibo\Bundle\CampusBundle\API\CampusAPI'
    public: true
    arguments:
      - '@universibo_campus.retriever.guzzle'
